### ISSUE TITLE
BuckyTools should preserve or sync mtime of metric files

### ISSUE THREAD

**Issue by grzkv** [go-graphite/buckytools#6]
Currently, every metric sync postpones cleanup of the data, because if metric was backfilled, its *mtime* changes to more recent.

Metric *mtime* should be either preserved or synced across the cluster so that cleanups happen properly.

**Comment by azhiltsov** [comment]
Voting for separate parameter at invocation for preservation of mtime+ctime

**Comment by deniszh** [comment]
👍 for separate parameter

**Comment by grzkv** [comment]
Agreed.
